Blocks:
  #BLOCKS
  # Add any items you want
  # As long as the block was not broken with silk touch, the user may get a reward.
  # You can use Essentials' /itemdb command to give you the block name.
  "COAL_ORE":
    # ODDS
    # Odds must be expressed in decimal and surrounded by brackets and quotation marks
    # Odds must be greater than 0 but no greater than 1
    # Odds must not have a 0 as the last numerical value
    "[0.1]":
    # COMMANDS
    # Use %PLAYER% as a placeholder for the players username
    - 'say Hello World'
    - 'msg %PLAYER% You mined a very lucky coal ore!'
    "[0.25]":
    - 'say A lucky coal ore was mined'
    "[1.0]":
    - 'say A coal ore was mined'
  "IRON_ORE":
    "[0.1]":
    - ''
  "GOLD_ORE":
    "[0.1]":
    - ''
  "DIAMOND_ORE":
    "[0.1]":
    - ''
  "EMERALD_ORE":
    "[0.1]":
    - ''
  "LAPIS_ORE":
    "[0.1]":
    - ''
  "NETHER_QUARTZ_ORE":
    "[0.1]":
    - ''
